package assignment05;
public enum Genre extends Book{
	FANTASY, SCIENCE_FICTION, WESTERN, ROMANCE,
	THRILLER, MYSTERY, DETECTIVE_STORY, DYSTOPIA,
	MEMOIR, BIOGRAPHY, PLAY, MUSICAL, SATIRE, HAIKU,
	HORROR, DIY, DICTIONARY, NON_FICTION
}
